# CoinAPI by GueniPlayz

# setup your mysql connection
mysql:
  host: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "password"

# general settings
settings:
  # enable/disable vault support
  vault: false
  # enable/disable placeholder_api support - Placeholders: %gcoinapi_coins%
  placeholder_api: false

  # update interval that saves coins into database
  update_interval:
    # the amount of seconds to wait before running the task for the first time
    period: 120
    # the amount of seconds to wait between the next run
    delay: 120